### ISSUE TITLE
npm page looks scary

### ISSUE THREAD

**Issue by stereobooster** [tadeuszwojcik/supertest-chai#1]
https://npmjs.org/package/chai-supertest

There is no git link, there is no Readme. So it gives impression of unsupported (abandoned) lib with no source.

PS the lib itself nice. Thanks for it

**Comment by tadeuszwojcik** [comment]
We use that lib on daily basis, for integration testing of express app, but you're right some more docs and improvements to npm registry are needed, hope to find some time in next week to do this.

Cheers,
Tadek

**Comment by tadeuszwojcik** [comment]
Just updated npm page (https://npmjs.org/package/supertest-chai), unfortunately I could not restore access to my old account, so I had to rename package to publish it on new account, incontinent I know, sorry about that.
