### ISSUE TITLE
Combinations and Syntax

### ISSUE THREAD

**Issue by dschinkel** [tadeuszwojcik/supertest-chai#5]
How do I know all of the combinations of chai expect or should that can be used.  For instance how does one know you can use .json, or what are all the possible http properties you can check (specific syntax) outside of the very minimal examples you show on the main page here?  Does one assume it's exactly the properties defined in https://github.com/chaijs/chai-http as you guys said this was inspired by that project?  I mean are you wrapping that project too?  How can I be sure to know all the things I can check and how?  Do you also use some supertest based assertions in your examples or is it all chai?  There are grey lines here...

**Comment by tadeuszwojcik** [comment]
Custom assertions are defined here https://github.com/tadeuszwojcik/supertest-chai/blob/master/lib/asserts.js, but for you can use standard chai asserts as well, for example res.body is a string so you can perform any string asserts defined by chai on in if you want. I'm not actively working on that project anymore, if you'd like to please send me pull request with readme update about that stuff. Cheers
