### ISSUE TITLE
Able to check json without supertest-chai

### ISSUE THREAD

**Issue by dschinkel** [tadeuszwojcik/supertest-chai#6]
I was able to check for json, with standard supertest and standard chai.  I didn't need to use supertest-chai, so what's the advantage here?

for example I was able to do this without supertest-chai:

```
var chai = require('chai'),
    should = chai.should(),
    var request = require('supertest')(app.koaApp.listen());

 var statusCode;
                var responseData;
                var body;
                var response;

                request.get(uri).end(function(err, result){
                    should.not.exist(err);

                    response = result;
                    body = result.body;
                    statusCode = result.statusCode;
                });

                it('the data should be in the form of a JSON object', function(done){
                    response.should.be.json;
                    done();
                });
```

no I'm not inlining the checks, I'm moving them out to params for my tests for a specific reason.  But point being I was able to use the syntax "should.be.json" without supertest-chai

**Comment by tadeuszwojcik** [comment]
If you're happy with supertest  please use it! Three years back when that lib was created supertest had many issues (especially with cookies persistence between requests which was deal breaker for me.
